### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by ludvighe** [Diskmaskin/sbserver#2]
SELECT product.name, product.nr, product.alcohol, product.price, product.volume, product.type, product.added, product.dropped, productGroup.name FROM product JOIN productGroup ON product.productGroupId = productGroup.id WHERE added between 2018-04-03 AND 2019-09-02;

Ovanstående sql-sats returnerar ingenting trots att det ska finnas datum däremellan.

**Comment by DarkSonic** [comment]
Kolumnen added i tabellen product sparar datum som TEXT, inte som INT. Därför kan inte between hämta data baserat på nummer utan måste hämta som strängar genom att sätta '  ' runt datum. 
M.a.o. added between '2018-04-03' AND '2019-09-02'

Korrekt syntax ser ut som följande:

SELECT product.name, product.nr, product.alcohol, product.price, product.volume, product.type, product.added, product.dropped, productGroup.name FROM product JOIN productGroup ON product.productGroupId = productGroup.id WHERE added between '2018-04-03' AND '2019-09-02';

Denna syntax har jag testat och kan därför säga att den fungerar.
